//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilidades.Mensajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeExcepcion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeExcepcion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilidades.Mensajes.MensajeExcepcion", typeof(MensajeExcepcion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado, su usuario no posee privilegios para realizar esta acción..
        /// </summary>
        public static string AccesoDenegadoAccion {
            get {
                return ResourceManager.GetString("AccesoDenegadoAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string AccesoDenegadoFormulario {
            get {
                return ResourceManager.GetString("AccesoDenegadoFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ConfiguracionLlaveNoEncontrada {
            get {
                return ResourceManager.GetString("ConfiguracionLlaveNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ConfiguracionLlaveValorInvalido {
            get {
                return ResourceManager.GetString("ConfiguracionLlaveValorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ConfiguracionSeccionNoEncontrada {
            get {
                return ResourceManager.GetString("ConfiguracionSeccionNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string EnumeracionValorInvalido {
            get {
                return ResourceManager.GetString("EnumeracionValorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorAutorizacion {
            get {
                return ResourceManager.GetString("ErrorAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorFinSuplantacion {
            get {
                return ResourceManager.GetString("ErrorFinSuplantacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorGuardarSesion {
            get {
                return ResourceManager.GetString("ErrorGuardarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorInicioSuplantacion {
            get {
                return ResourceManager.GetString("ErrorInicioSuplantacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrorUsuarioSuplantacion {
            get {
                return ResourceManager.GetString("ErrorUsuarioSuplantacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string EtapaNoEncontrada {
            get {
                return ResourceManager.GetString("EtapaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string IdentificadorObjetoCreacion {
            get {
                return ResourceManager.GetString("IdentificadorObjetoCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string IdentificadorObjetoCreacionListado {
            get {
                return ResourceManager.GetString("IdentificadorObjetoCreacionListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string IdentificadorObjetoNoValido {
            get {
                return ResourceManager.GetString("IdentificadorObjetoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string IdentificadorObjetoNoValidoListado {
            get {
                return ResourceManager.GetString("IdentificadorObjetoNoValidoListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ParametroEnNulo {
            get {
                return ResourceManager.GetString("ParametroEnNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ParametroListaVacia {
            get {
                return ResourceManager.GetString("ParametroListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ParametroVacio {
            get {
                return ResourceManager.GetString("ParametroVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ReferenciaEnNulo {
            get {
                return ResourceManager.GetString("ReferenciaEnNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string RegistroDesbloqueado {
            get {
                return ResourceManager.GetString("RegistroDesbloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string RegistroNoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string SesionInactiva {
            get {
                return ResourceManager.GetString("SesionInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string TiempoEsperaAgotado {
            get {
                return ResourceManager.GetString("TiempoEsperaAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string UsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNoEncontrado", resourceCulture);
            }
        }
    }
}
