//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDato.Sql.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public Catalogo()
        {
            this.Valor = new HashSet<Valor>();
        }
    
        public short IdCatalogo { get; set; }
        public string CodigoInterno { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool EsReservado { get; set; }
        public bool EstaActivo { get; set; }
        public int IdUsuarioCracion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Valor> Valor { get; set; }
    }
}
