//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDato.Sql.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaNatural
    {
        public int IdPersonaNatural { get; set; }
        public int IdPersona { get; set; }
        public int IdGenero { get; set; }
        public int IdEstadoCivil { get; set; }
        public int IdOcupacion { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string TercerNombre { get; set; }
        public string CuartoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string NombreCompleto { get; set; }
        public string ApellidoDeCasada { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool EstaActivo { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Valor Valor { get; set; }
        public virtual Valor Valor1 { get; set; }
        public virtual Valor Valor2 { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
