//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDato.Sql.Modelo {
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PruebaSoftEntidades:DbContext {
        public PruebaSoftEntidades()
            : base("name=PruebaSoftEntidades") {
        }
        public PruebaSoftEntidades(DbConnection Conexion)
            : base(Conexion, true) {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<PersonaNatural> PersonaNaturales { get; set; }
        public DbSet<Valor> Valores { get; set; }
        public DbSet<Catalogo> Catalogos { get; set; }
        public DbSet<Persona> Personas { get; set; }
    }
}
