//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDato.Sql.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor
    {
        public Valor()
        {
            this.PersonaNatural = new HashSet<PersonaNatural>();
            this.PersonaNatural1 = new HashSet<PersonaNatural>();
            this.PersonaNatural2 = new HashSet<PersonaNatural>();
        }
    
        public int IdValor { get; set; }
        public short IdCatalogo { get; set; }
        public string CodigoInterno { get; set; }
        public string ValorCatalogo { get; set; }
        public string Descripcion { get; set; }
        public short Orden { get; set; }
        public bool EstaActivo { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<PersonaNatural> PersonaNatural { get; set; }
        public virtual ICollection<PersonaNatural> PersonaNatural1 { get; set; }
        public virtual ICollection<PersonaNatural> PersonaNatural2 { get; set; }
        public virtual Catalogo Catalogo { get; set; }
    }
}
